### ISSUE TITLE
Documentation build fails on existing installations

### ISSUE THREAD

**Issue by gmazoyer** [gmazoyer/ansible-role-netbox#19]
The following step appears to be failing on existing installation, not new ones though.

```yaml
  - name: build documentation
    ansible.builtin.command: "{{ netbox_virtualenv_path }}/bin/mkdocs build"
    args:
      chdir: "{{ netbox_install_directory }}"
    become: true
    become_user: "{{ netbox_user }}"
```

The error is the following:

```
INFO     -  Cleaning site directory
INFO     -  Building documentation to directory: /opt/netbox/netbox/project-static/docs
INFO     -  The following pages exist in the docs directory, but are not included in the "nav" configuration:
              - index.md
/opt/netbox/venv/lib/python3.9/site-packages/mkdocstrings/handlers/python/__init__.py:13: UserWarning: The 'python-legacy' extra of mkdocstrings will become mandatory in the next release. We have no way to detect if you already specify it, so if you do, please ignore this warning. You can globally disable it with the PYTHONWARNINGS environment variable: PYTHONWARNINGS=ignore::UserWarning:mkdocstrings.handlers.python
  warnings.warn(
ERROR    -  mkdocstrings: __init__() got an unexpected keyword argument 'heading_level'
            Traceback (most recent call last):
              File "/opt/netbox/venv/lib/python3.9/site-packages/pytkdocs/cli.py", line 205, in main
                output = json.dumps(process_json(line))
              File "/opt/netbox/venv/lib/python3.9/site-packages/pytkdocs/cli.py", line 114, in process_json
                return process_config(json.loads(json_input))
              File "/opt/netbox/venv/lib/python3.9/site-packages/pytkdocs/cli.py", line 89, in process_config
                loader = Loader(**obj_config)
            TypeError: __init__() got an unexpected keyword argument 'heading_level'
ERROR    -  Error reading page 'plugins/development/forms.md':
ERROR    -  Could not collect 'utilities.forms.ColorField'

Aborted with a BuildError!
```

**Comment by gmazoyer** [comment]
Maybe an issue on my test VM, reinstalling it from scratch solved the issue.
